export const ADD_NOTE = 'ADD_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
export const CHANGE_NOTE_FIELD = 'CHANGE_NOTE_FIELD'
export const CLEAR = 'CLEAR'
export const EDIT_MODE = 'EDIT_MODE'
export const EDIT_SWITCH = 'EDIT_SWITCH'
export const EDIT_NOTE = 'EDIT_NOTE'
export const SAVE_EDIT_NOTE = 'SAVE_EDIT_NOTE'